// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ROC
SEXP ROC(SEXP Ranswer, SEXP Restimate);
RcppExport SEXP FastROC_ROC(SEXP RanswerSEXP, SEXP RestimateSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Ranswer(RanswerSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Restimate(RestimateSEXP );
        SEXP __result = ROC(Ranswer, Restimate);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
